### ISSUE TITLE
iCE40-HX8K-EVN

### ISSUE THREAD

**Issue by n24bass** [abnoname/iceZ0mb1e#1]
Hello, 

I am very interested in this project.
I tried it with the iCE40-hx8k-evn board, but it does not work as expected.
In the makefile, I changed from "TARGET = 5k" to "TARGET = 8k", no output from UART, no change LED status.
I would appreciate your advice.

Best regards.

**Comment by abnoname** [comment]
Thanks for reporting. There seems to be an issue with larger used ROM. This problem has to be debugged soon. At this time I disabled some graphic functions inside the ssd1306 lib that I added later after testing the HX8K. Now the system is running as expected:

make clean && make fpga TARGET=8k && make flash TARGET=8k

**Comment by n24bass** [comment]
Thanks for the advice. This program worked by removing ssd1306 routines. However, the behavior is quite unstable on my HK8K breakout board.
