### ISSUE TITLE
Add SystemVerilog Support

### ISSUE THREAD

**Issue by jwrr** [abnoname/iceZ0mb1e#6]
SystemVerilog has added a do-while loop, so 'do' is now a reserved word.  The TV80's Data Output bus is named 'do' which causes a compilation error when using icarus -g2012 (systemverilog partial support).  I'm using cocotb for testing and it uses the -g2012 switch.
 
I have created a branch that changes 'do' to 'data_output'.  To keep consistent naming I also changed 'di' to 'data_in'.  If you're interested, I have created a pull request. Best Regards.
 
ps: with these changes, the simulation runs well in cocotb.

**Comment by abnoname** [comment]
thanks :-)
