### ISSUE TITLE
spi corner-case

### ISSUE THREAD

**Issue by jwrr** [abnoname/iceZ0mb1e#7]
I'm writing a randomized testbench for your design written in python using cocotb.  The test found a corner-case in spi rtl, that happens when changing spi_clk frequency from slow to fast.  In this case the clock divider counts a long time and eventually wraps at 256 causing the busy-check polling loop to fail. Typically the clk_div is constant so this issue most-likely  won't occur in real scenarios.  The randomized test showed the bug.  The fix is in the Pull Request's branch jwrr/systemverilog.  Please let me know if more info is needed. thanks

**Comment by abnoname** [comment]
thanks for finding out :-)
